# Generated by Django 5.1.3 on 2024-12-02 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_codinglanguage_speakinglanguage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.language'),
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='coding_languages',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='speaking_languages',
        ),
        migrations.AddField(
            model_name='tutor',
            name='languages',
            field=models.ManyToManyField(related_name='tutors', to='tutorials.language'),
        ),
        migrations.DeleteModel(
            name='CodingLanguage',
        ),
        migrations.DeleteModel(
            name='SpeakingLanguage',
        ),
    ]
