# Generated by Django 5.1.4 on 2024-12-04 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tutorials.tutor', verbose_name='Tutor'),
        ),
        migrations.AddField(
            model_name='booking',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tutorials.specialization', verbose_name='Specialization'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='specialized_tutors', to='tutorials.specialization'),
        ),
    ]
