# Generated by Django 5.1.4 on 2024-12-05 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_booking_tutor_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_bookings', to='tutorials.tutor'),
        ),
    ]
