# Generated by Django 5.1.3 on 2024-12-02 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_language_tutor_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='languages',
        ),
        migrations.AddField(
            model_name='tutor',
            name='coding_languages',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='tutorials.codinglanguage'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.codinglanguage'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='speaking_languages',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='tutorials.speakinglanguage'),
        ),
    ]
