# Generated by Django 5.1.3 on 2024-12-03 00:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_alter_booking_language_remove_tutor_coding_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['term__start_date', 'start_time'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Duration of each lesson (e.g., 1 hour)', verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='booking',
            name='frequency',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Fortnightly', 'Fortnightly')], default='Weekly', max_length=15, verbose_name='Frequency'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default=datetime.time(10, 0), verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tutorials.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_student', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_as_tutor', to='tutorials.tutor', verbose_name='Tutor'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration', models.DurationField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.booking')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='term',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tutorials.term', verbose_name='Term'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Accepted')), fields=('tutor', 'term', 'start_time'), name='unique_tutor_booking_per_time'),
        ),
    ]
