# Generated by Django 5.1.3 on 2024-12-03 00:21

from django.db import migrations



def add_languages(apps, schema_editor):
    Language = apps.get_model('tutorials', 'Language')
    languages = ['Python', 'JavaScript', 'Ruby', 'Java', 'C++']
    for name in languages:
        Language.objects.create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_term_alter_booking_options_and_more'),  # Replace with your last migration file
    ]

    operations = [
        migrations.RunPython(add_languages),
    ]