# Generated by Django 5.1.3 on 2024-12-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_auto_20241203_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='experience_level',
            field=models.TextField(blank=True, help_text='Describe your coding experience level in 100 words or less.', max_length=500, verbose_name='Experience Level'),
        ),
    ]
