# Generated by Django 5.1.3 on 2024-12-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['term__start_date', 'day_of_week', 'start_time'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_tutor_booking_per_time',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Accepted')), fields=('tutor', 'term', 'day_of_week', 'start_time'), name='unique_tutor_booking_per_time'),
        ),
    ]
