# Generated by Django 5.1.3 on 2024-12-03 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0009_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorials.term'),
        ),
    ]
