# Generated by Django 5.1.4 on 2024-12-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_specialization_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='student_approval',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10, verbose_name='Student Approval'),
        ),
    ]
