# Generated by Django 5.1.4 on 2024-12-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0011_booking_student_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tutor_approval',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10, verbose_name='Tutor Approval'),
        ),
    ]
