# Generated by Django 5.1.4 on 2024-12-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0014_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='languages',
            field=models.ManyToManyField(related_name='specializations', to='tutorials.language'),
        ),
    ]
