# Generated by Django 5.1.4 on 2024-12-12 15:01

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0015_specialization_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='name',
            field=models.CharField(choices=[('September-Christmas', 'September-Christmas'), ('January-Easter', 'January-Easter'), ('May-July', 'May-July')], help_text='Select the term from the given options.', max_length=50),
        ),
        migrations.CreateModel(
            name='TutorAvalibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=56)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tutorials.term')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tutorials.tutor')),
            ],
        ),
    ]
