# Generated by Django 5.1.4 on 2024-12-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0016_alter_term_name_tutoravalibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutoravalibility',
            options={'verbose_name': 'Tutor Availability', 'verbose_name_plural': 'Tutor Availabilities'},
        ),
    ]
